// documentation/modules/examples/counter/components/vue/widget/vue/widget.vue
<template>
  <div class="list">
    <div class="item" @click='add'>
      <h3>Vue counter </h3>
      <span>clicks here: {{ result }}</span>
    </div>
  </div>
</template>

<script lang="ts">
import {updateCount} from "@beyond/docs/examples/sm/actions";

export default {
  data() {
    return {
      result: 0
    }
  },
  methods: {
    emitResult() {
      ++this.result;
      this.$emit('input', this.result)
    },
    add() {
      this.emitResult();
      updateCount();
    }
  }
}
</script>

<style lang="sass" scoped>
</style>

// documentation/modules/examples/counter/components/react/widget/ts/views/widget.tsx
import * as React from "react";
import {updateCount} from "@beyond/docs/examples-sm-actions";

export /*bundle*/
function Widget() {
    const [count, setCount] = React.useState(0);
    const add = () => {
        setCount(count + 1);
        updateCount();
    };

    return (
        <div className="list">
            <div className="item" onClick={add}>
                <h3>React counter</h3>
                <span>clicks here: {count}</span>
            </div>
        </div>
    );
}
